# Generated by Django 2.0.3 on 2018-03-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bucketlist',
        ),
    ]
